#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"
	
test -e test.png && rm test.png

jupyter labextension install @jupyterlab/latex@0.6.1
jupyter labextension enable --py @jupyterlab/latex@0.6.1

pip install jupyterlab-git
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git

jupyter lab build

# build font caches
mtxrun --script fonts --reload
luaotfload-tool --update

# remember git login credentials
git config --global credential.helper "cache --timeout 144000"
git clone https://github.com/mathematicalmichael/jsm19 && cd jsm19/
