#!/bin/bash

jupyter labextension install @jupyterlab/latex@0.6.1
jupyter labextension enable --py @jupyterlab/latex@0.6.1

pip install jupyterlab-git
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git

jupyter lab build

# build font caches
#mtxrun --script fonts --reload
#luaotfload-tool --update

# remember git login credentials
git config --global credential.helper "cache --timeout 144000"
