#!/bin/bash

jupyter labextension install @jupyterlab/latex@0.6.1
jupyter labextension enable --sys-prefix @jupyterlab/latex@0.6.1
jupyter labextension install @jupyterlab/git
pip install jupyterlab-git
jupyter serverextension enable --py jupyterlab_git

